import type { FAQItem } from "@/content/schemas";

export const faqs: FAQItem[] = [
  { id: "faq-1", category: "Registration", question: "How do I register for Hack the Cube?", answer: "Registration will be conducted through our official online registration portal. Fill in your team and participant details, college information, preferred technical track, and complete the process. Confirmation will be sent by the organizing committee." },
  { id: "faq-2", category: "Registration", question: "What is the registration fee?", answer: "The registration fee will be announced before registrations open. The final amount will be determined based on event budget, sponsorship support, food arrangements, and infrastructure requirements." },
  { id: "faq-3", category: "Eligibility", question: "Who can participate?", answer: "Any currently enrolled student from a recognized college or university across India can participate. Students from all engineering and technology branches are welcome, irrespective of their year of study." },
  { id: "faq-4", category: "Team Size", question: "What is the team size?", answer: "Participants will compete in teams. The final minimum and maximum team size will be confirmed before registrations open. Each participant can register as a member of only one team." },
  { id: "faq-5", category: "Event Structure", question: "How is the hackathon structured?", answer: "The event begins with an inauguration ceremony featuring 3 interactive podcast-style speaker sessions (30 min discussion + 15 min Q&A each). After a lunch break, the 24-hour hackathon runs from 3:30 PM Day 1 to 3:30 PM Day 2, with mentor evaluation, 2 formal judging rounds, and a grand finale." },
  { id: "faq-6", category: "Tracks", question: "How many tracks and problem statements are there?", answer: "The hackathon has 3 major technical tracks, each with 6 problem statements — totaling 18 problem statements. Each track has its own set of mentors and a dedicated 4-judge panel. Track domains will be finalized based on industry trends and sponsor input." },
  { id: "faq-7", category: "Evaluation", question: "How will projects be judged?", answer: "Evaluation has 3 phases: (1) Mentor Evaluation during the initial development phase, (2) Evaluation Round 1 at 8:00 AM on Day 2, and (3) Evaluation Round 2 at 3:30 PM. Projects are scored on Innovation, Technical Complexity, Feasibility, Impact, and Presentation. Each track has 4 judges." },
  { id: "faq-8", category: "Prizes", question: "What are the prizes?", answer: "The total cash prize pool is ₹1,50,000 distributed across 3 tracks: ₹35,000 for each Track Winner and ₹15,000 for each Track Runner-Up. Additionally, 2 teams will receive Special Recognition Awards with exclusive goodies. A total of 8 teams will be recognized." },
  { id: "faq-9", category: "Food", question: "Will food be provided?", answer: "Yes! Food arrangements may include evening refreshments, dinner, midnight snacks, breakfast, lunch, drinking water, and tea/coffee at regular intervals throughout the 24-hour hackathon." },
  { id: "faq-10", category: "Accommodation", question: "Is accommodation available?", answer: "The hackathon venue is open 24 hours with designated resting areas. Separate arrangements may be made as required per institutional policies." },
  { id: "faq-11", category: "Certificates", question: "Will certificates be provided?", answer: "Yes, certificates may include: Winner Certificate, Runner-Up Certificate, Participation Certificate, Mentor Appreciation Certificate, Judge Appreciation Certificate, and Volunteer/Organizing Committee Certificate." },
  { id: "faq-12", category: "Internet", question: "Will WiFi be available?", answer: "Yes, reliable high-speed internet and Wi-Fi will be provided. The venue will have adequate electrical points, extension boards, and continuous power availability with backup arrangements." },
  { id: "faq-13", category: "Laptop Requirements", question: "Do I need to bring my own laptop?", answer: "Yes, participants must bring their own laptops, chargers, and any other hardware they may need. Dedicated development areas with tables, chairs, and charging points will be provided." },
  { id: "faq-14", category: "Mentorship", question: "How does the mentorship program work?", answer: "Experienced DIT alumni and industry professionals will serve as mentors. They will evaluate whether teams have correctly understood their problem statement and guide them on solution approach, technology selection, architecture, and feasibility. Mentor evaluations are formally recorded and contribute to the team's overall score." },
  { id: "faq-15", category: "Speaker Sessions", question: "What is the podcast-style speaker format?", answer: "Instead of conventional speeches, each of the 3 speaker sessions follows a podcast-style format: a 30-minute interactive discussion followed by a 15-minute live Q&A. Questions are primarily collected from registered participants via Google Form before the event." },
];
